markdown: kramdown
highlighter: rouge
permalink: blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: page/:num
gems: [jekyll-paginate]

blog:
    name: 贺鑫                                                    # 博客名称
    description: 个人博客                                         # 博客描述
    title: 时光之笔                                               # 网页标题
    url: yuxingmo.github.io                                       # 博客地址
    qiniu:                                                        # 七牛云地址
author:
    name: 贺鑫                                               # 作者名称
    email: yuxingmohust@gmail.com                            # 邮箱地址
    weibo: http://weibo.com/p/1005053054094863               # 微博地址
    微信:  yuxingmo                                          # 微信号
    logo: http://i4.piimg.com/8311/91cf7ca953056210.jpg      # logo地址
    url: yuxingmo.github.io                                  # 博客地址
    douban: 
        name:                                               # 豆瓣地址名称
        key:                                                # 豆瓣API Key

